//! The version string every build reports, and link configuration for everything cargo itself LINKS
//! on the developer's own machine — the host UI simulator, and the host TEST BINARY. (The install
//! identities and the localization catalog are generated by the platform layer's own build script,
//! `platform/build.rs`.)
//!
//! Version generation runs for EVERY build. Host link configuration is a **no-op for the build
//! that ships**: the television binary is linked by the Makefile, not by cargo (the ARM archive is a
//! staticlib; a staticlib has no link step), so the ARM cross build reaches the early return in
//! `build_support/host_link.rs` (`host_link::emit`) and emits nothing further.
//!
//! **The gate is the TARGET, not the `hostsim` feature, and that distinction was paid for.** It
//! used to be the feature, on the reasoning that the simulator is "the only configuration that
//! links anything here" — which was true only for as long as no host test reached the drawing
//! layer. `cargo test --lib` builds an executable too, and macOS `ld64` dead-strips BEFORE it
//! reports undefined symbols, so a test binary that never made `gfx`/`text`/`svg` reachable linked
//! happily against nothing but libSystem. Restructure phase 5b ended that: `app/bridge.rs`'s tests
//! stand up the REAL rig — `Bridge` holds a `text::TtfMeasure`, and a real `Dispatcher` mounts real
//! screens whose `draw` bodies call `gfx` — so those atoms are live, their `extern "C"` GL/SDL_ttf
//! /nanosvg references become hard undefined symbols, and the default `make check` pass stopped
//! linking. Gating on the target instead means any host build that cargo links gets what it needs,
//! whether or not somebody remembered a feature flag; CI already installs `libsdl2-dev`,
//! `libsdl2-ttf-dev` and `libgl1-mesa-dev` before `make check` for exactly this reason.
//!
//! Why a build script rather than `.cargo/config.toml`, which is where this crate's other
//! target-bound flags live: the library search path is not a constant. Homebrew is at
//! `/opt/homebrew` on Apple Silicon and `/usr/local` on Intel, while Linux distributions publish
//! their SDL locations through pkg-config. A hardcoded guess fails as an "SDL2 not found" link
//! error a long way from its cause.

use std::path::{Path, PathBuf};
use std::process::Command;

#[path = "build_support/host_link.rs"]
mod host_link;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build_support/host_link.rs");
    emit_version();
    emit_build_sha();

    // Host link configuration (SDL, GL, the nanosvg object): shared with the gfx layer's build
    // script, which needs the same lines for its own test binary.
    host_link::emit(Path::new(env!("CARGO_MANIFEST_DIR")).parent().expect("rust-modules has a parent"));
}

/// Publish `NJ_VERSION` — the version this build REPORTS, which is not always the version it was
/// cut from.
///
/// `Cargo.toml`, `pkg/appinfo.json` and `ipkroot/ctl/control` all carry the same three integers,
/// and `ci/check-package.py` fails the build if they ever disagree: LG accepts nothing else in a
/// package, so the published number has to stay exactly `X.Y.Z`. But a release commit leaves the
/// tree AT the version it just published, so every developer build after it reported that number
/// as its own — to `X-Plex-Version` on the account's authorized-devices list, to Sentry as the
/// release `nativejelly@X.Y.Z`, to PostHog as `app_version`, and on the diagnostics panel that is
/// meant to be photographed into a bug report. A crash from somebody's working tree landed on the
/// shipped release's tally and nothing downstream could separate the two.
///
/// So a build that is not a release names the version it is working TOWARDS and says what it is:
/// `0.5.0` published, `0.6.0-dev` in the tree.
///
/// **It is the next MINOR, because this project is trunk-based.** Trunk is where features land, so
/// the next thing cut from it is a minor (or a major, when the maintainer decides that); a PATCH is
/// only ever cut from an existing minor's own line, where trunk's number is not the question being
/// asked. Naming the next patch would therefore be wrong in the common case and right in none —
/// `0.5.1-dev` on trunk claims to be heading for a release that, by policy, is not cut from trunk
/// at all. It also makes the semver ordering mean something: `0.6.0-dev` precedes `0.6.0`, so the
/// tree really is a pre-release of what it is heading for, rather than of a version nobody plans.
///
/// A MAJOR is not guessed at, and cannot be: nothing in this file can see that decision, and
/// `1.0.0-dev` claimed on every ordinary build would be a false promise rather than a cautious one.
/// The invariant that actually matters is weaker and is preserved either way — the reported version
/// must never be a number a release has already used.
///
/// **A maintenance line signals itself with a tracked marker file, `RELEASE_LINE`** (repo root,
/// sibling of this crate — `../RELEASE_LINE` from `CARGO_MANIFEST_DIR`), rather than a git branch
/// lookup: a build script that reads git state is wrong in a tarball, in CI's detached-HEAD
/// checkout, and in a worktree whose branch name says nothing about the line it was cut for. The
/// file is absent on trunk, so trunk's behavior above is unchanged when it is missing. Present, it
/// names the line's `X.Y` (e.g. `0.6`), and a dev build on that line reports the next PATCH rather
/// than the next minor — `0.6.1-dev` after `0.6.0` — because on a maintenance line trunk's
/// "next minor" question does not apply at all.
///
/// **The suffix reaches the reported string ONLY.** It never enters `pkg/appinfo.json` or the
/// control file: `1.0.0-rc1` is not installable on a webOS television, which is also why
/// `ci/bump-version.py` refuses to write anything but three integers. `ci/check-package.py`
/// gates the other direction — a package built for the stable id may not carry a `-dev` binary.
///
/// **`NJ_CHANNEL=nightly` adds a third arm**, on top of `NJ_RELEASE`: a nightly build is always
/// a `RELEASE=1` build (no dev triggers ever ship under that id — see the Makefile's
/// `release-guard`), but it must not claim to BE the release its own `Cargo.toml` names, the same
/// reason a plain dev build cannot. So it reports the same "next minor, or next patch on a
/// maintenance line" number the `-dev` suffix would, dated instead of merely suffixed:
/// `0.7.0-nightly-20260919` rather than `0.7.0-dev`. The date comes from `NJ_NIGHTLY_DATE`
/// (`YYYYMMDD`, validated by [`is_nightly_date`]) because a bare channel name cannot tell two
/// nightly cuts of the same commit-less trunk apart — X-Plex-Version, the Sentry release and the
/// diagnostics panel all need that to distinguish "today's nightly" from "yesterday's" the way
/// `NJ_BUILD_SHA` cannot (trunk moves several times a day; the reported version is what a bug
/// report actually names).
///
/// The input is `NJ_RELEASE` and (new) `NJ_CHANNEL`/`NJ_NIGHTLY_DATE`, exported by the Makefile
/// for `RELEASE=1` and `FLAVOR=nightly` respectively and by nothing else, so the developer answer
/// is what an ordinary `make`, `make check`, `make sim` or a bare `cargo build` produces —
/// `NJ_CHANNEL` unset (or empty) leaves every existing build byte-for-byte as it always reported.
/// `rerun-if-env-changed` makes cargo re-run this when any of the three flips; the emitted value is
/// itself tracked, so the crate rebuilds with it.
fn emit_version() {
    println!("cargo:rerun-if-env-changed=NJ_RELEASE");
    println!("cargo:rerun-if-env-changed=NJ_CHANNEL");
    println!("cargo:rerun-if-env-changed=NJ_NIGHTLY_DATE");
    let pkg = std::env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION");
    // PARSED BEFORE THE BRANCH, deliberately. Validating only inside the developer arm would make
    // the shape rule conditional on the build that is least likely to be looked at: cargo accepts
    // `0.5.0-rc.1` in a manifest, LG accepts it in no package at all, and a release build is
    // exactly where that must not compile quietly.
    // On trunk the patch component is validated and then discarded (see the trunk arm below); on
    // a maintenance line it is exactly what the next dev version is built from.
    let (major, minor, patch) = triplet(&pkg);
    // Set-but-empty is not "release": the Makefile exports the variable only for a release build,
    // but a caller's shell or a CI step may still hand it over blank, and blank must mean what
    // unset means — the same shape `telemetry::sender` reads its credentials with. `NJ_CHANNEL`
    // follows the identical convention (see the Makefile's `override … := $(if …)` beside
    // `NJ_RELEASE`), so "nightly" is checked the same way rather than a second one.
    let release = std::env::var("NJ_RELEASE").is_ok_and(|v| !v.is_empty());
    let channel = std::env::var("NJ_CHANNEL").unwrap_or_default();
    if !channel.is_empty() && channel != "nightly" {
        panic!("NJ_CHANNEL={channel:?} is not a recognized channel — only \"nightly\" (or unset/empty) is");
    }
    let nightly = channel == "nightly";
    if nightly && !release {
        panic!(
            "NJ_CHANNEL=nightly requires NJ_RELEASE=1 — nightly never ships a dev build (see \
             the Makefile's release-guard)"
        );
    }
    let version = if nightly {
        let date = std::env::var("NJ_NIGHTLY_DATE").unwrap_or_default();
        if !is_nightly_date(&date) {
            panic!(
                "NJ_CHANNEL=nightly requires NJ_NIGHTLY_DATE as exactly 8 digits (YYYYMMDD); \
                 got {date:?}"
            );
        }
        let (next_major, next_minor, next_patch) = next_triplet(major, minor, patch, pkg.as_str());
        format!("{next_major}.{next_minor}.{next_patch}-nightly-{date}")
    } else if release {
        pkg
    } else {
        let (next_major, next_minor, next_patch) = next_triplet(major, minor, patch, pkg.as_str());
        format!("{next_major}.{next_minor}.{next_patch}-dev")
    };
    println!("cargo:rustc-env=NJ_VERSION={version}");
}

/// The `(major, minor, patch)` this checkout's tree is heading TOWARDS — trunk's next minor with
/// the patch reset, or a maintenance line's next patch on its own major.minor. Shared by the plain
/// `-dev` suffix and the nightly `-nightly-<date>` one: both name the same target version, they
/// just spell it differently. Mirrored in Python by `ci/version_rule.py::next_version_triplet`,
/// which `ci/check-package.py` and `ci/flavor.py` both import rather than re-deriving this a third
/// and fourth time.
fn next_triplet(major: u64, minor: u64, patch: u64, pkg: &str) -> (u64, u64, u64) {
    if let Some((line_major, line_minor)) = release_line() {
        // A maintenance line: the next thing cut from it is a PATCH, on the same major.minor —
        // `0.6.1` after `0.6.0`, never a minor bump this line will never make.
        (line_major, line_minor, dev_patch(patch, pkg))
    } else {
        // Trunk: discarded rather than incremented. The next thing cut from trunk is a minor, and
        // `0.5.3` + a minor is `0.6.0`, not `0.6.3`.
        //
        // `u64` and `checked_add` so the three implementations of this arithmetic agree on every
        // input rather than on realistic ones: cargo's own semver allows components up to
        // `u64::MAX`, and python's integers are unbounded, so a narrower type here would be the
        // one of the three that answers differently. Unreachable for any version anyone writes,
        // which is exactly why it should not be a silent wrap.
        let next = minor
            .checked_add(1)
            .unwrap_or_else(|| panic!("Cargo.toml version {pkg:?} has no next minor"));
        (major, next, 0)
    }
}

// `dev_patch` and `parse_release_line` used to be defined right here, each with its own
// `#[cfg(test)]` module beside it. Cargo never compiles a build script as a test target, so
// those tests silently never ran under `cargo test --lib` (either feature pass of `make check`)
// or the PR gate. They now live in `src/release_line.rs`, where `cargo test --lib` genuinely
// compiles and runs them, and this `include!` pulls in that exact source so `emit_version` still
// has both functions, from a single definition rather than a drifting second copy.
include!("src/release_line.rs");

/// The maintenance line this checkout is cut for, as `(major, minor)`, or `None` on trunk.
///
/// Reads the tracked `RELEASE_LINE` marker at the repo root (`../RELEASE_LINE` from
/// `CARGO_MANIFEST_DIR`) — present ONLY on a maintenance branch, absent everywhere else. Absence
/// (no file, unreadable, or malformed content) is not an error: it means "trunk", which is the
/// overwhelmingly common case and must stay byte-identical to before this existed.
fn release_line() -> Option<(u64, u64)> {
    let repo = Path::new(env!("CARGO_MANIFEST_DIR")).parent()?;
    let path = repo.join("RELEASE_LINE");
    // Watch the marker ONLY while it exists. A `rerun-if-changed` path that is MISSING is stale on
    // every invocation (cargo logs "stale: missing .../RELEASE_LINE"), so emitting it on trunk,
    // where the file is absent by design, re-ran this script and recompiled the whole app crate on
    // every build however little had changed. The transitions are still covered:
    //   * present -> edited or removed: the path was watched, so its mtime or disappearance reruns;
    //   * absent -> present: a `git checkout`/`switch`/`reset`/`pull` onto a line that carries the
    //     marker moves this worktree's `HEAD` and its reflog, which `emit_build_sha` watches.
    // The one case left unwatched: creating the marker by hand, uncommitted, in a tree whose `HEAD`
    // does not move (or in a `.git`-less source tarball); `touch rust-modules/build.rs` forces the
    // rerun. Releases and nightlies are built from a CI checkout with an empty target dir, so no
    // shipped artifact can inherit a stale answer; the marker only ever changes the `-dev` /
    // nightly string, never a stable release's version, and `ci/check-package.py`'s packaged-binary
    // version check is the backstop if a stale one were ever packaged.
    if path.exists() {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    let content = std::fs::read_to_string(&path).ok()?;
    parse_release_line(&content)
}

/// The manifest version as three integers, or a build failure.
///
/// A version that is not three integers is a hard error rather than a passthrough: every gate in
/// `ci/` asserts that shape, so reaching here with anything else means the manifest was edited by
/// hand into a state that cannot be packaged, and failing at the build is where that costs least.
fn triplet(pkg: &str) -> (u64, u64, u64) {
    let parts: Vec<&str> = pkg.split('.').collect();
    // Split first, parse second, and drop NOTHING in between: a `filter_map(parse)` reads as the
    // same thing and is not — `0.5.0-rc.1` splits into four parts, one of which does not parse,
    // and silently becomes (0, 5, 1). The shape has to fail, not degrade.
    let [major, minor, patch] = parts[..] else {
        panic!("Cargo.toml version {pkg:?} is not three dot-separated integers");
    };
    let int = |part: &str| {
        part.parse()
            .unwrap_or_else(|_| panic!("Cargo.toml version {pkg:?} is not three integers"))
    };
    (int(major), int(minor), int(patch))
}

/// Publish `NJ_BUILD_SHA` — the short commit this binary was built from, so the About screen can
/// name the exact source a bug report came from. `NJ_VERSION` alone cannot: every commit on trunk
/// between two releases reports the identical `X.Y.0-dev`.
///
/// Best-effort and NOT [`emit_version`]'s contract: a release source package (`docs/distribution.md`
/// publishes one per release) has no `.git` at all and must still build, so a failed `git` falls
/// back to `"unknown"` rather than failing the build the way an unparsable `Cargo.toml` version
/// does. Re-run on whatever moves this WORKTREE's `HEAD` — a commit, checkout or rebase all touch
/// its reflog — via `git rev-parse --git-path`, which resolves `logs/HEAD`/`HEAD` under the linked
/// worktree's own `.git/worktrees/<name>/`, not the main checkout's; watching the wrong one would
/// silently miss every commit made from here.
fn emit_build_sha() {
    let sha = git_short_sha().unwrap_or_else(|| "unknown".into());
    println!("cargo:rustc-env=NJ_BUILD_SHA={sha}");
    for rel in ["logs/HEAD", "HEAD"] {
        // Only a file that exists: a MISSING rerun-if-changed path is stale on every invocation
        // (see `release_line`), and `logs/HEAD` is absent in a repository with
        // `core.logAllRefUpdates=false` or a deleted reflog. `HEAD` itself still moves on checkout.
        if let Some(path) = git_path(rel).filter(|p| p.exists()) {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
}

fn git_short_sha() -> Option<String> {
    let out = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let sha = String::from_utf8(out.stdout).ok()?;
    let sha = sha.trim();
    (!sha.is_empty()).then(|| sha.to_string())
}

/// The absolute path `git` resolves `<rel>` (a path inside `.git`) to for the CURRENT worktree.
fn git_path(rel: &str) -> Option<PathBuf> {
    let out = Command::new("git")
        .args(["rev-parse", "--path-format=absolute", "--git-path", rel])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let p = String::from_utf8(out.stdout).ok()?;
    Some(PathBuf::from(p.trim()))
}
